language: python
sudo: required
dist: xenial
python:
  - "3.8"
#  - "nightly"
before_install:
#  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script:
 - isort -c -rc
 - pycodestyle lotto/ tests/ *.py*
 - xvfb-run nosetests --with-coverage --cover-erase --cover-package=lotto --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=5bacd9172ec14e95b08854b3eaf6365d
  - python-codacy-coverage -r coverage.xml
