language: python
os: linux
dist: bionic
services:
  - xvfb
python:
  - "3.9"
#  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script:
 - isort . --diff
 - pycodestyle lotto/ tests/ *.py*
 - QT_QPA_PLATFORM=offscreen xvfb-run -a --server-args="-screen 0 1024x768x24" nosetests --with-coverage --cover-erase --cover-package=lotto --cover-html
after_success:
  - coverage report -m
  - coverage xml
  - export CODACY_PROJECT_TOKEN=5bacd9172ec14e95b08854b3eaf6365d
  - python-codacy-coverage -r coverage.xml
