# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotto_dateneing.ui'
#
# Created: Sun Jul 24 10:54:23 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(859, 646)
        self.Lottozahlen = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lottozahlen.sizePolicy().hasHeightForWidth())
        self.Lottozahlen.setSizePolicy(sizePolicy)
        self.Lottozahlen.setMinimumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lottozahlen.setFont(font)
        self.Lottozahlen.setAutoFillBackground(False)
        self.Lottozahlen.setStyleSheet(_fromUtf8("QFrame#Rahmen { border-image: url(:/lottokugel.png);}\n"
"QLabel {    background-color: rgb(195, 195, 195)}"))
        self.Lottozahlen.setObjectName(_fromUtf8("Lottozahlen"))
        self.gridLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 444, 251))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Btn_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_2.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_2.setAutoFillBackground(True)
        self.Btn_2.setObjectName(_fromUtf8("Btn_2"))
        self.gridLayout.addWidget(self.Btn_2, 0, 1, 1, 1)
        self.Btn_16 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_16.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_16.setAutoFillBackground(True)
        self.Btn_16.setObjectName(_fromUtf8("Btn_16"))
        self.gridLayout.addWidget(self.Btn_16, 4, 1, 1, 1)
        self.Btn_8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_8.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_8.setAutoFillBackground(True)
        self.Btn_8.setObjectName(_fromUtf8("Btn_8"))
        self.gridLayout.addWidget(self.Btn_8, 2, 0, 1, 1)
        self.Btn_10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_10.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_10.setAutoFillBackground(True)
        self.Btn_10.setObjectName(_fromUtf8("Btn_10"))
        self.gridLayout.addWidget(self.Btn_10, 2, 2, 1, 1)
        self.Btn_1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_1.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_1.setAutoFillBackground(True)
        self.Btn_1.setObjectName(_fromUtf8("Btn_1"))
        self.gridLayout.addWidget(self.Btn_1, 0, 0, 1, 1)
        self.Btn_15 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_15.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_15.setAutoFillBackground(True)
        self.Btn_15.setObjectName(_fromUtf8("Btn_15"))
        self.gridLayout.addWidget(self.Btn_15, 4, 0, 1, 1)
        self.Btn_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_3.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_3.setAutoFillBackground(True)
        self.Btn_3.setObjectName(_fromUtf8("Btn_3"))
        self.gridLayout.addWidget(self.Btn_3, 0, 2, 1, 1)
        self.Btn_4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_4.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_4.setAutoFillBackground(True)
        self.Btn_4.setObjectName(_fromUtf8("Btn_4"))
        self.gridLayout.addWidget(self.Btn_4, 0, 3, 1, 1)
        self.Btn_5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_5.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_5.setAutoFillBackground(True)
        self.Btn_5.setObjectName(_fromUtf8("Btn_5"))
        self.gridLayout.addWidget(self.Btn_5, 0, 4, 1, 1)
        self.Btn_22 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_22.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_22.setAutoFillBackground(True)
        self.Btn_22.setObjectName(_fromUtf8("Btn_22"))
        self.gridLayout.addWidget(self.Btn_22, 6, 0, 1, 1)
        self.Btn_29 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_29.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_29.setAutoFillBackground(True)
        self.Btn_29.setObjectName(_fromUtf8("Btn_29"))
        self.gridLayout.addWidget(self.Btn_29, 7, 0, 1, 1)
        self.Btn_9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_9.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_9.setAutoFillBackground(True)
        self.Btn_9.setObjectName(_fromUtf8("Btn_9"))
        self.gridLayout.addWidget(self.Btn_9, 2, 1, 1, 1)
        self.Btn_11 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_11.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_11.setAutoFillBackground(True)
        self.Btn_11.setObjectName(_fromUtf8("Btn_11"))
        self.gridLayout.addWidget(self.Btn_11, 2, 3, 1, 1)
        self.Btn_6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_6.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_6.setAutoFillBackground(True)
        self.Btn_6.setObjectName(_fromUtf8("Btn_6"))
        self.gridLayout.addWidget(self.Btn_6, 0, 5, 1, 1)
        self.Btn_23 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_23.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_23.setAutoFillBackground(True)
        self.Btn_23.setObjectName(_fromUtf8("Btn_23"))
        self.gridLayout.addWidget(self.Btn_23, 6, 1, 1, 1)
        self.Btn_30 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_30.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_30.setAutoFillBackground(True)
        self.Btn_30.setObjectName(_fromUtf8("Btn_30"))
        self.gridLayout.addWidget(self.Btn_30, 7, 1, 1, 1)
        self.Btn_24 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_24.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_24.setAutoFillBackground(True)
        self.Btn_24.setObjectName(_fromUtf8("Btn_24"))
        self.gridLayout.addWidget(self.Btn_24, 6, 2, 1, 1)
        self.Btn_31 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_31.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_31.setAutoFillBackground(True)
        self.Btn_31.setObjectName(_fromUtf8("Btn_31"))
        self.gridLayout.addWidget(self.Btn_31, 7, 2, 1, 1)
        self.Btn_36 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_36.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_36.setAutoFillBackground(True)
        self.Btn_36.setObjectName(_fromUtf8("Btn_36"))
        self.gridLayout.addWidget(self.Btn_36, 8, 0, 1, 1)
        self.Btn_43 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_43.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_43.setAutoFillBackground(True)
        self.Btn_43.setObjectName(_fromUtf8("Btn_43"))
        self.gridLayout.addWidget(self.Btn_43, 9, 0, 1, 1)
        self.Btn_37 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_37.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_37.setAutoFillBackground(True)
        self.Btn_37.setObjectName(_fromUtf8("Btn_37"))
        self.gridLayout.addWidget(self.Btn_37, 8, 1, 1, 1)
        self.Btn_38 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_38.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_38.setAutoFillBackground(True)
        self.Btn_38.setObjectName(_fromUtf8("Btn_38"))
        self.gridLayout.addWidget(self.Btn_38, 8, 2, 1, 1)
        self.Btn_18 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_18.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_18.setAutoFillBackground(True)
        self.Btn_18.setObjectName(_fromUtf8("Btn_18"))
        self.gridLayout.addWidget(self.Btn_18, 4, 3, 1, 1)
        self.Btn_25 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_25.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_25.setAutoFillBackground(True)
        self.Btn_25.setObjectName(_fromUtf8("Btn_25"))
        self.gridLayout.addWidget(self.Btn_25, 6, 3, 1, 1)
        self.Btn_32 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_32.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_32.setAutoFillBackground(True)
        self.Btn_32.setObjectName(_fromUtf8("Btn_32"))
        self.gridLayout.addWidget(self.Btn_32, 7, 3, 1, 1)
        self.Btn_39 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_39.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_39.setAutoFillBackground(True)
        self.Btn_39.setObjectName(_fromUtf8("Btn_39"))
        self.gridLayout.addWidget(self.Btn_39, 8, 3, 1, 1)
        self.Btn_7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_7.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_7.setAutoFillBackground(True)
        self.Btn_7.setObjectName(_fromUtf8("Btn_7"))
        self.gridLayout.addWidget(self.Btn_7, 0, 6, 1, 1)
        self.Btn_12 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_12.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_12.setAutoFillBackground(True)
        self.Btn_12.setObjectName(_fromUtf8("Btn_12"))
        self.gridLayout.addWidget(self.Btn_12, 2, 4, 1, 1)
        self.Btn_35 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_35.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_35.setAutoFillBackground(True)
        self.Btn_35.setObjectName(_fromUtf8("Btn_35"))
        self.gridLayout.addWidget(self.Btn_35, 7, 6, 1, 1)
        self.Btn_42 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_42.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_42.setAutoFillBackground(True)
        self.Btn_42.setObjectName(_fromUtf8("Btn_42"))
        self.gridLayout.addWidget(self.Btn_42, 8, 6, 1, 1)
        self.Btn_49 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_49.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_49.setAutoFillBackground(True)
        self.Btn_49.setObjectName(_fromUtf8("Btn_49"))
        self.gridLayout.addWidget(self.Btn_49, 9, 6, 1, 1)
        self.Btn_48 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_48.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_48.setAutoFillBackground(True)
        self.Btn_48.setObjectName(_fromUtf8("Btn_48"))
        self.gridLayout.addWidget(self.Btn_48, 9, 5, 1, 1)
        self.Btn_47 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_47.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_47.setAutoFillBackground(True)
        self.Btn_47.setObjectName(_fromUtf8("Btn_47"))
        self.gridLayout.addWidget(self.Btn_47, 9, 4, 1, 1)
        self.Btn_41 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_41.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_41.setAutoFillBackground(True)
        self.Btn_41.setObjectName(_fromUtf8("Btn_41"))
        self.gridLayout.addWidget(self.Btn_41, 8, 5, 1, 1)
        self.Btn_28 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_28.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_28.setAutoFillBackground(True)
        self.Btn_28.setObjectName(_fromUtf8("Btn_28"))
        self.gridLayout.addWidget(self.Btn_28, 6, 6, 1, 1)
        self.Btn_14 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_14.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_14.setAutoFillBackground(True)
        self.Btn_14.setObjectName(_fromUtf8("Btn_14"))
        self.gridLayout.addWidget(self.Btn_14, 2, 6, 1, 1)
        self.Btn_13 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_13.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_13.setAutoFillBackground(True)
        self.Btn_13.setObjectName(_fromUtf8("Btn_13"))
        self.gridLayout.addWidget(self.Btn_13, 2, 5, 1, 1)
        self.Btn_19 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_19.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_19.setAutoFillBackground(True)
        self.Btn_19.setObjectName(_fromUtf8("Btn_19"))
        self.gridLayout.addWidget(self.Btn_19, 4, 4, 1, 1)
        self.Btn_20 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_20.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_20.setAutoFillBackground(True)
        self.Btn_20.setObjectName(_fromUtf8("Btn_20"))
        self.gridLayout.addWidget(self.Btn_20, 4, 5, 1, 1)
        self.Btn_26 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_26.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_26.setAutoFillBackground(True)
        self.Btn_26.setObjectName(_fromUtf8("Btn_26"))
        self.gridLayout.addWidget(self.Btn_26, 6, 4, 1, 1)
        self.Btn_27 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_27.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_27.setAutoFillBackground(True)
        self.Btn_27.setObjectName(_fromUtf8("Btn_27"))
        self.gridLayout.addWidget(self.Btn_27, 6, 5, 1, 1)
        self.Btn_34 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_34.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_34.setAutoFillBackground(True)
        self.Btn_34.setObjectName(_fromUtf8("Btn_34"))
        self.gridLayout.addWidget(self.Btn_34, 7, 5, 1, 1)
        self.Btn_33 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_33.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_33.setAutoFillBackground(True)
        self.Btn_33.setObjectName(_fromUtf8("Btn_33"))
        self.gridLayout.addWidget(self.Btn_33, 7, 4, 1, 1)
        self.Btn_40 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_40.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_40.setAutoFillBackground(True)
        self.Btn_40.setObjectName(_fromUtf8("Btn_40"))
        self.gridLayout.addWidget(self.Btn_40, 8, 4, 1, 1)
        self.Btn_46 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_46.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_46.setAutoFillBackground(True)
        self.Btn_46.setObjectName(_fromUtf8("Btn_46"))
        self.gridLayout.addWidget(self.Btn_46, 9, 3, 1, 1)
        self.Btn_45 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_45.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_45.setAutoFillBackground(True)
        self.Btn_45.setObjectName(_fromUtf8("Btn_45"))
        self.gridLayout.addWidget(self.Btn_45, 9, 2, 1, 1)
        self.Btn_44 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_44.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_44.setAutoFillBackground(True)
        self.Btn_44.setObjectName(_fromUtf8("Btn_44"))
        self.gridLayout.addWidget(self.Btn_44, 9, 1, 1, 1)
        self.Btn_21 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_21.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_21.setAutoFillBackground(True)
        self.Btn_21.setObjectName(_fromUtf8("Btn_21"))
        self.gridLayout.addWidget(self.Btn_21, 4, 6, 1, 1)
        self.Btn_17 = QtGui.QPushButton(self.gridLayoutWidget)
        self.Btn_17.setMaximumSize(QtCore.QSize(58, 16777215))
        self.Btn_17.setAutoFillBackground(True)
        self.Btn_17.setObjectName(_fromUtf8("Btn_17"))
        self.gridLayout.addWidget(self.Btn_17, 4, 2, 1, 1)
        self.edi_daten_gewinnz = QtGui.QPlainTextEdit(self.Lottozahlen)
        self.edi_daten_gewinnz.setGeometry(QtCore.QRect(470, 30, 381, 151))
        self.edi_daten_gewinnz.setAutoFillBackground(False)
        self.edi_daten_gewinnz.setUndoRedoEnabled(False)
        self.edi_daten_gewinnz.setReadOnly(True)
        self.edi_daten_gewinnz.setObjectName(_fromUtf8("edi_daten_gewinnz"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 441, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.spinBox_1 = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_1.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_1.setMaximum(49)
        self.spinBox_1.setObjectName(_fromUtf8("spinBox_1"))
        self.horizontalLayout.addWidget(self.spinBox_1)
        self.spinBox_2 = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_2.setMaximum(49)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.spinBox_3 = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_3.setMaximum(49)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout.addWidget(self.spinBox_3)
        self.spinBox_4 = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_4.setMaximum(49)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.spinBox_5 = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_5.setMaximum(49)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout.addWidget(self.spinBox_5)
        self.spinBox_6 = QtGui.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.spinBox_6.setMaximum(49)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout.addWidget(self.spinBox_6)
        self.calendarWidget = QtGui.QCalendarWidget(self.Lottozahlen)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 420, 441, 181))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.Btn_hinzu = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_hinzu.setGeometry(QtCore.QRect(220, 260, 231, 25))
        self.Btn_hinzu.setObjectName(_fromUtf8("Btn_hinzu"))
        self.Btn_gz_loeschen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_gz_loeschen.setGeometry(QtCore.QRect(750, 240, 91, 25))
        self.Btn_gz_loeschen.setObjectName(_fromUtf8("Btn_gz_loeschen"))
        self.Btn_gz_auswerten = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_gz_auswerten.setGeometry(QtCore.QRect(470, 240, 91, 25))
        self.Btn_gz_auswerten.setObjectName(_fromUtf8("Btn_gz_auswerten"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 441, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.spinBox_7 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_7.setGeometry(QtCore.QRect(130, 360, 51, 23))
        self.spinBox_7.setMaximum(49)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.pushButton_7 = QtGui.QPushButton(self.Lottozahlen)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 360, 41, 21))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.lab_zusatz = QtGui.QLabel(self.Lottozahlen)
        self.lab_zusatz.setGeometry(QtCore.QRect(10, 360, 101, 21))
        self.lab_zusatz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_zusatz.setObjectName(_fromUtf8("lab_zusatz"))
        self.spinBox_superz = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_superz.setGeometry(QtCore.QRect(360, 360, 51, 23))
        self.spinBox_superz.setMaximum(9)
        self.spinBox_superz.setObjectName(_fromUtf8("spinBox_superz"))
        self.lab_superz = QtGui.QLabel(self.Lottozahlen)
        self.lab_superz.setGeometry(QtCore.QRect(240, 360, 91, 21))
        self.lab_superz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_superz.setObjectName(_fromUtf8("lab_superz"))
        self.spinBox_spiel77 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_spiel77.setGeometry(QtCore.QRect(130, 390, 101, 23))
        self.spinBox_spiel77.setMaximum(9999999)
        self.spinBox_spiel77.setObjectName(_fromUtf8("spinBox_spiel77"))
        self.lab_spiel77 = QtGui.QLabel(self.Lottozahlen)
        self.lab_spiel77.setGeometry(QtCore.QRect(10, 390, 101, 21))
        self.lab_spiel77.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_spiel77.setObjectName(_fromUtf8("lab_spiel77"))
        self.spinBox_super6 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_super6.setGeometry(QtCore.QRect(360, 390, 91, 23))
        self.spinBox_super6.setMaximum(999999)
        self.spinBox_super6.setObjectName(_fromUtf8("spinBox_super6"))
        self.lab_super6 = QtGui.QLabel(self.Lottozahlen)
        self.lab_super6.setGeometry(QtCore.QRect(240, 390, 91, 21))
        self.lab_super6.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_super6.setObjectName(_fromUtf8("lab_super6"))
        self.com_modus = QtGui.QComboBox(self.Lottozahlen)
        self.com_modus.setGeometry(QtCore.QRect(10, 260, 151, 25))
        self.com_modus.setObjectName(_fromUtf8("com_modus"))
        self.com_modus.addItem(_fromUtf8(""))
        self.com_modus.addItem(_fromUtf8(""))
        self.Btn_Zufall = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_Zufall.setGeometry(QtCore.QRect(30, 370, 151, 25))
        self.Btn_Zufall.setObjectName(_fromUtf8("Btn_Zufall"))
        self.com_laufzeit = QtGui.QComboBox(self.Lottozahlen)
        self.com_laufzeit.setGeometry(QtCore.QRect(270, 380, 121, 25))
        self.com_laufzeit.setObjectName(_fromUtf8("com_laufzeit"))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.lab_laufzeit = QtGui.QLabel(self.Lottozahlen)
        self.lab_laufzeit.setGeometry(QtCore.QRect(280, 360, 69, 18))
        self.lab_laufzeit.setObjectName(_fromUtf8("lab_laufzeit"))
        self.Btn_ls_loeschen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_ls_loeschen.setGeometry(QtCore.QRect(750, 560, 91, 25))
        self.Btn_ls_loeschen.setObjectName(_fromUtf8("Btn_ls_loeschen"))
        self.Btn_ls_auswerten = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_ls_auswerten.setGeometry(QtCore.QRect(470, 560, 91, 25))
        self.Btn_ls_auswerten.setObjectName(_fromUtf8("Btn_ls_auswerten"))
        self.edi_daten_lottoschein = QtGui.QPlainTextEdit(self.Lottozahlen)
        self.edi_daten_lottoschein.setGeometry(QtCore.QRect(470, 340, 381, 161))
        self.edi_daten_lottoschein.setAutoFillBackground(False)
        self.edi_daten_lottoschein.setUndoRedoEnabled(False)
        self.edi_daten_lottoschein.setReadOnly(True)
        self.edi_daten_lottoschein.setObjectName(_fromUtf8("edi_daten_lottoschein"))
        self.label = QtGui.QLabel(self.Lottozahlen)
        self.label.setGeometry(QtCore.QRect(610, 310, 121, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.Lottozahlen)
        self.label_2.setGeometry(QtCore.QRect(600, 0, 111, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lab_daten_gewinnz = QtGui.QLabel(self.Lottozahlen)
        self.lab_daten_gewinnz.setGeometry(QtCore.QRect(470, 180, 381, 51))
        self.lab_daten_gewinnz.setObjectName(_fromUtf8("lab_daten_gewinnz"))
        self.lab_daten_lottoschein = QtGui.QLabel(self.Lottozahlen)
        self.lab_daten_lottoschein.setGeometry(QtCore.QRect(470, 500, 381, 51))
        self.lab_daten_lottoschein.setObjectName(_fromUtf8("lab_daten_lottoschein"))
        self.Btn_gz_anzeigen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_gz_anzeigen.setGeometry(QtCore.QRect(620, 240, 98, 25))
        self.Btn_gz_anzeigen.setObjectName(_fromUtf8("Btn_gz_anzeigen"))
        self.Btn_ls_anzeigen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_ls_anzeigen.setGeometry(QtCore.QRect(620, 560, 98, 25))
        self.Btn_ls_anzeigen.setObjectName(_fromUtf8("Btn_ls_anzeigen"))
        MainWindow.setCentralWidget(self.Lottozahlen)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionHilfe = QtGui.QAction(MainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionHilfe)
        self.menuHilfe.addAction(self.actionInfo)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edi_daten_gewinnz, self.calendarWidget)
        MainWindow.setTabOrder(self.calendarWidget, self.Btn_hinzu)
        MainWindow.setTabOrder(self.Btn_hinzu, self.Btn_gz_auswerten)
        MainWindow.setTabOrder(self.Btn_gz_auswerten, self.Btn_gz_loeschen)
        MainWindow.setTabOrder(self.Btn_gz_loeschen, self.com_modus)
        MainWindow.setTabOrder(self.com_modus, self.Btn_Zufall)
        MainWindow.setTabOrder(self.Btn_Zufall, self.spinBox_1)
        MainWindow.setTabOrder(self.spinBox_1, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.spinBox_3)
        MainWindow.setTabOrder(self.spinBox_3, self.spinBox_4)
        MainWindow.setTabOrder(self.spinBox_4, self.spinBox_5)
        MainWindow.setTabOrder(self.spinBox_5, self.spinBox_6)
        MainWindow.setTabOrder(self.spinBox_6, self.spinBox_7)
        MainWindow.setTabOrder(self.spinBox_7, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.com_laufzeit)
        MainWindow.setTabOrder(self.com_laufzeit, self.spinBox_superz)
        MainWindow.setTabOrder(self.spinBox_superz, self.spinBox_spiel77)
        MainWindow.setTabOrder(self.spinBox_spiel77, self.spinBox_super6)
        MainWindow.setTabOrder(self.spinBox_super6, self.Btn_1)
        MainWindow.setTabOrder(self.Btn_1, self.Btn_2)
        MainWindow.setTabOrder(self.Btn_2, self.Btn_3)
        MainWindow.setTabOrder(self.Btn_3, self.Btn_4)
        MainWindow.setTabOrder(self.Btn_4, self.Btn_5)
        MainWindow.setTabOrder(self.Btn_5, self.Btn_6)
        MainWindow.setTabOrder(self.Btn_6, self.Btn_7)
        MainWindow.setTabOrder(self.Btn_7, self.Btn_8)
        MainWindow.setTabOrder(self.Btn_8, self.Btn_9)
        MainWindow.setTabOrder(self.Btn_9, self.Btn_10)
        MainWindow.setTabOrder(self.Btn_10, self.Btn_11)
        MainWindow.setTabOrder(self.Btn_11, self.Btn_12)
        MainWindow.setTabOrder(self.Btn_12, self.Btn_13)
        MainWindow.setTabOrder(self.Btn_13, self.Btn_14)
        MainWindow.setTabOrder(self.Btn_14, self.Btn_15)
        MainWindow.setTabOrder(self.Btn_15, self.Btn_16)
        MainWindow.setTabOrder(self.Btn_16, self.Btn_17)
        MainWindow.setTabOrder(self.Btn_17, self.Btn_18)
        MainWindow.setTabOrder(self.Btn_18, self.Btn_19)
        MainWindow.setTabOrder(self.Btn_19, self.Btn_20)
        MainWindow.setTabOrder(self.Btn_20, self.Btn_21)
        MainWindow.setTabOrder(self.Btn_21, self.Btn_22)
        MainWindow.setTabOrder(self.Btn_22, self.Btn_23)
        MainWindow.setTabOrder(self.Btn_23, self.Btn_24)
        MainWindow.setTabOrder(self.Btn_24, self.Btn_25)
        MainWindow.setTabOrder(self.Btn_25, self.Btn_26)
        MainWindow.setTabOrder(self.Btn_26, self.Btn_27)
        MainWindow.setTabOrder(self.Btn_27, self.Btn_28)
        MainWindow.setTabOrder(self.Btn_28, self.Btn_29)
        MainWindow.setTabOrder(self.Btn_29, self.Btn_30)
        MainWindow.setTabOrder(self.Btn_30, self.Btn_31)
        MainWindow.setTabOrder(self.Btn_31, self.Btn_32)
        MainWindow.setTabOrder(self.Btn_32, self.Btn_33)
        MainWindow.setTabOrder(self.Btn_33, self.Btn_34)
        MainWindow.setTabOrder(self.Btn_34, self.Btn_35)
        MainWindow.setTabOrder(self.Btn_35, self.Btn_36)
        MainWindow.setTabOrder(self.Btn_36, self.Btn_37)
        MainWindow.setTabOrder(self.Btn_37, self.Btn_38)
        MainWindow.setTabOrder(self.Btn_38, self.Btn_39)
        MainWindow.setTabOrder(self.Btn_39, self.Btn_40)
        MainWindow.setTabOrder(self.Btn_40, self.Btn_41)
        MainWindow.setTabOrder(self.Btn_41, self.Btn_42)
        MainWindow.setTabOrder(self.Btn_42, self.Btn_43)
        MainWindow.setTabOrder(self.Btn_43, self.Btn_44)
        MainWindow.setTabOrder(self.Btn_44, self.Btn_45)
        MainWindow.setTabOrder(self.Btn_45, self.Btn_46)
        MainWindow.setTabOrder(self.Btn_46, self.Btn_47)
        MainWindow.setTabOrder(self.Btn_47, self.Btn_48)
        MainWindow.setTabOrder(self.Btn_48, self.Btn_49)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.Lottozahlen.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_16.setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_10.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_15.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_22.setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_29.setText(QtGui.QApplication.translate("MainWindow", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_11.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_23.setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_30.setText(QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_24.setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_31.setText(QtGui.QApplication.translate("MainWindow", "31", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_36.setText(QtGui.QApplication.translate("MainWindow", "36", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_43.setText(QtGui.QApplication.translate("MainWindow", "43", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_37.setText(QtGui.QApplication.translate("MainWindow", "37", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_38.setText(QtGui.QApplication.translate("MainWindow", "38", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_18.setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_25.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_32.setText(QtGui.QApplication.translate("MainWindow", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_39.setText(QtGui.QApplication.translate("MainWindow", "39", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_12.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_35.setText(QtGui.QApplication.translate("MainWindow", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_42.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_49.setText(QtGui.QApplication.translate("MainWindow", "49", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_48.setText(QtGui.QApplication.translate("MainWindow", "48", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_47.setText(QtGui.QApplication.translate("MainWindow", "47", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_41.setText(QtGui.QApplication.translate("MainWindow", "41", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_28.setText(QtGui.QApplication.translate("MainWindow", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_14.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_13.setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_19.setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_20.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_26.setText(QtGui.QApplication.translate("MainWindow", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_27.setText(QtGui.QApplication.translate("MainWindow", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_34.setText(QtGui.QApplication.translate("MainWindow", "34", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_33.setText(QtGui.QApplication.translate("MainWindow", "33", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_40.setText(QtGui.QApplication.translate("MainWindow", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_46.setText(QtGui.QApplication.translate("MainWindow", "46", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_45.setText(QtGui.QApplication.translate("MainWindow", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_44.setText(QtGui.QApplication.translate("MainWindow", "44", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_21.setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_17.setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_gewinnz.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_hinzu.setText(QtGui.QApplication.translate("MainWindow", "zur Datenbank hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_auswerten.setText(QtGui.QApplication.translate("MainWindow", "Auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_zusatz.setText(QtGui.QApplication.translate("MainWindow", "Zusatzzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_superz.setText(QtGui.QApplication.translate("MainWindow", "Superzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_spiel77.setText(QtGui.QApplication.translate("MainWindow", "Spiel 77", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_super6.setText(QtGui.QApplication.translate("MainWindow", "Super 6:", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gewinnzahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(1, QtGui.QApplication.translate("MainWindow", "Lottoschein", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_Zufall.setText(QtGui.QApplication.translate("MainWindow", "Zufallszahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(0, QtGui.QApplication.translate("MainWindow", "unbegrenzt", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 Ziehung", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(3, QtGui.QApplication.translate("MainWindow", "3 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(4, QtGui.QApplication.translate("MainWindow", "4 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(5, QtGui.QApplication.translate("MainWindow", "5 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(6, QtGui.QApplication.translate("MainWindow", "6 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(7, QtGui.QApplication.translate("MainWindow", "7 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(8, QtGui.QApplication.translate("MainWindow", "8 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(9, QtGui.QApplication.translate("MainWindow", "9 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(10, QtGui.QApplication.translate("MainWindow", "10 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_laufzeit.setText(QtGui.QApplication.translate("MainWindow", "Laufzeit:", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_auswerten.setText(QtGui.QApplication.translate("MainWindow", "Auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_lottoschein.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lottoschein:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Gewinnzahlen:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_gewinnz.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_lottoschein.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe.setText(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))

