# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotto_dateneing.ui'
#
# Created: Sat Apr 21 12:25:02 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(859, 646)
        self.Lottozahlen = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lottozahlen.sizePolicy().hasHeightForWidth())
        self.Lottozahlen.setSizePolicy(sizePolicy)
        self.Lottozahlen.setMinimumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lottozahlen.setFont(font)
        self.Lottozahlen.setAutoFillBackground(False)
        self.Lottozahlen.setStyleSheet(_fromUtf8("QFrame#Rahmen { border-image: url(:/lottokugel.png);}\n"
"QLabel {    background-color: rgb(195, 195, 195)}"))
        self.Lottozahlen.setObjectName(_fromUtf8("Lottozahlen"))
        self.gridLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 444, 251))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edi_daten_gewinnz = QtGui.QPlainTextEdit(self.Lottozahlen)
        self.edi_daten_gewinnz.setGeometry(QtCore.QRect(470, 30, 381, 151))
        self.edi_daten_gewinnz.setAutoFillBackground(False)
        self.edi_daten_gewinnz.setUndoRedoEnabled(False)
        self.edi_daten_gewinnz.setReadOnly(True)
        self.edi_daten_gewinnz.setObjectName(_fromUtf8("edi_daten_gewinnz"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 290, 441, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.calendarWidget = QtGui.QCalendarWidget(self.Lottozahlen)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 420, 441, 181))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.Btn_hinzu = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_hinzu.setGeometry(QtCore.QRect(220, 260, 231, 25))
        self.Btn_hinzu.setObjectName(_fromUtf8("Btn_hinzu"))
        self.Btn_gz_loeschen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_gz_loeschen.setGeometry(QtCore.QRect(750, 240, 91, 25))
        self.Btn_gz_loeschen.setObjectName(_fromUtf8("Btn_gz_loeschen"))
        self.Btn_gz_auswerten = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_gz_auswerten.setGeometry(QtCore.QRect(470, 240, 91, 25))
        self.Btn_gz_auswerten.setObjectName(_fromUtf8("Btn_gz_auswerten"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 441, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lab_zusatz = QtGui.QLabel(self.Lottozahlen)
        self.lab_zusatz.setGeometry(QtCore.QRect(10, 360, 101, 21))
        self.lab_zusatz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_zusatz.setObjectName(_fromUtf8("lab_zusatz"))
        self.spinBox_superz = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_superz.setGeometry(QtCore.QRect(360, 360, 51, 23))
        self.spinBox_superz.setMaximum(9)
        self.spinBox_superz.setObjectName(_fromUtf8("spinBox_superz"))
        self.lab_superz = QtGui.QLabel(self.Lottozahlen)
        self.lab_superz.setGeometry(QtCore.QRect(240, 360, 91, 21))
        self.lab_superz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_superz.setObjectName(_fromUtf8("lab_superz"))
        self.spinBox_spiel77 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_spiel77.setGeometry(QtCore.QRect(130, 390, 101, 23))
        self.spinBox_spiel77.setMaximum(9999999)
        self.spinBox_spiel77.setObjectName(_fromUtf8("spinBox_spiel77"))
        self.lab_spiel77 = QtGui.QLabel(self.Lottozahlen)
        self.lab_spiel77.setGeometry(QtCore.QRect(10, 390, 101, 21))
        self.lab_spiel77.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_spiel77.setObjectName(_fromUtf8("lab_spiel77"))
        self.spinBox_super6 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_super6.setGeometry(QtCore.QRect(360, 390, 91, 23))
        self.spinBox_super6.setMaximum(999999)
        self.spinBox_super6.setObjectName(_fromUtf8("spinBox_super6"))
        self.lab_super6 = QtGui.QLabel(self.Lottozahlen)
        self.lab_super6.setGeometry(QtCore.QRect(240, 390, 91, 21))
        self.lab_super6.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_super6.setObjectName(_fromUtf8("lab_super6"))
        self.com_modus = QtGui.QComboBox(self.Lottozahlen)
        self.com_modus.setGeometry(QtCore.QRect(10, 260, 151, 25))
        self.com_modus.setObjectName(_fromUtf8("com_modus"))
        self.com_modus.addItem(_fromUtf8(""))
        self.com_modus.addItem(_fromUtf8(""))
        self.Btn_Zufall = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_Zufall.setGeometry(QtCore.QRect(30, 370, 151, 25))
        self.Btn_Zufall.setObjectName(_fromUtf8("Btn_Zufall"))
        self.com_laufzeit = QtGui.QComboBox(self.Lottozahlen)
        self.com_laufzeit.setGeometry(QtCore.QRect(270, 380, 121, 25))
        self.com_laufzeit.setObjectName(_fromUtf8("com_laufzeit"))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.lab_laufzeit = QtGui.QLabel(self.Lottozahlen)
        self.lab_laufzeit.setGeometry(QtCore.QRect(280, 360, 69, 18))
        self.lab_laufzeit.setObjectName(_fromUtf8("lab_laufzeit"))
        self.Btn_ls_loeschen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_ls_loeschen.setGeometry(QtCore.QRect(750, 560, 91, 25))
        self.Btn_ls_loeschen.setObjectName(_fromUtf8("Btn_ls_loeschen"))
        self.Btn_ls_auswerten = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_ls_auswerten.setGeometry(QtCore.QRect(470, 560, 91, 25))
        self.Btn_ls_auswerten.setObjectName(_fromUtf8("Btn_ls_auswerten"))
        self.edi_daten_lottoschein = QtGui.QPlainTextEdit(self.Lottozahlen)
        self.edi_daten_lottoschein.setGeometry(QtCore.QRect(470, 340, 381, 161))
        self.edi_daten_lottoschein.setAutoFillBackground(False)
        self.edi_daten_lottoschein.setUndoRedoEnabled(False)
        self.edi_daten_lottoschein.setReadOnly(True)
        self.edi_daten_lottoschein.setObjectName(_fromUtf8("edi_daten_lottoschein"))
        self.label = QtGui.QLabel(self.Lottozahlen)
        self.label.setGeometry(QtCore.QRect(610, 310, 121, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.Lottozahlen)
        self.label_2.setGeometry(QtCore.QRect(600, 0, 111, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lab_daten_gewinnz = QtGui.QLabel(self.Lottozahlen)
        self.lab_daten_gewinnz.setGeometry(QtCore.QRect(470, 180, 381, 51))
        self.lab_daten_gewinnz.setObjectName(_fromUtf8("lab_daten_gewinnz"))
        self.lab_daten_lottoschein = QtGui.QLabel(self.Lottozahlen)
        self.lab_daten_lottoschein.setGeometry(QtCore.QRect(470, 500, 381, 51))
        self.lab_daten_lottoschein.setObjectName(_fromUtf8("lab_daten_lottoschein"))
        self.Btn_gz_anzeigen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_gz_anzeigen.setGeometry(QtCore.QRect(620, 240, 98, 25))
        self.Btn_gz_anzeigen.setObjectName(_fromUtf8("Btn_gz_anzeigen"))
        self.Btn_ls_anzeigen = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_ls_anzeigen.setGeometry(QtCore.QRect(620, 560, 98, 25))
        self.Btn_ls_anzeigen.setObjectName(_fromUtf8("Btn_ls_anzeigen"))
        MainWindow.setCentralWidget(self.Lottozahlen)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionHilfe = QtGui.QAction(MainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionHilfe)
        self.menuHilfe.addAction(self.actionInfo)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edi_daten_gewinnz, self.calendarWidget)
        MainWindow.setTabOrder(self.calendarWidget, self.Btn_hinzu)
        MainWindow.setTabOrder(self.Btn_hinzu, self.Btn_gz_auswerten)
        MainWindow.setTabOrder(self.Btn_gz_auswerten, self.Btn_gz_loeschen)
        MainWindow.setTabOrder(self.Btn_gz_loeschen, self.com_modus)
        MainWindow.setTabOrder(self.com_modus, self.Btn_Zufall)
        MainWindow.setTabOrder(self.Btn_Zufall, self.com_laufzeit)
        MainWindow.setTabOrder(self.com_laufzeit, self.spinBox_superz)
        MainWindow.setTabOrder(self.spinBox_superz, self.spinBox_spiel77)
        MainWindow.setTabOrder(self.spinBox_spiel77, self.spinBox_super6)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.Lottozahlen.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_gewinnz.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_hinzu.setText(QtGui.QApplication.translate("MainWindow", "zur Datenbank hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_auswerten.setText(QtGui.QApplication.translate("MainWindow", "Auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_zusatz.setText(QtGui.QApplication.translate("MainWindow", "Zusatzzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_superz.setText(QtGui.QApplication.translate("MainWindow", "Superzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_spiel77.setText(QtGui.QApplication.translate("MainWindow", "Spiel 77", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_super6.setText(QtGui.QApplication.translate("MainWindow", "Super 6:", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gewinnzahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(1, QtGui.QApplication.translate("MainWindow", "Lottoschein", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_Zufall.setText(QtGui.QApplication.translate("MainWindow", "Zufallszahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(0, QtGui.QApplication.translate("MainWindow", "unbegrenzt", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 Ziehung", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(3, QtGui.QApplication.translate("MainWindow", "3 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(4, QtGui.QApplication.translate("MainWindow", "4 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(5, QtGui.QApplication.translate("MainWindow", "5 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(6, QtGui.QApplication.translate("MainWindow", "6 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(7, QtGui.QApplication.translate("MainWindow", "7 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(8, QtGui.QApplication.translate("MainWindow", "8 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(9, QtGui.QApplication.translate("MainWindow", "9 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(10, QtGui.QApplication.translate("MainWindow", "10 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_laufzeit.setText(QtGui.QApplication.translate("MainWindow", "Laufzeit:", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_auswerten.setText(QtGui.QApplication.translate("MainWindow", "Auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_lottoschein.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lottoschein:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Gewinnzahlen:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_gewinnz.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_lottoschein.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe.setText(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))

