# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotto_dateneing.ui'
#
# Created: Wed Jun 12 23:05:20 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(913, 564)
        self.Lottozahlen = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lottozahlen.sizePolicy().hasHeightForWidth())
        self.Lottozahlen.setSizePolicy(sizePolicy)
        self.Lottozahlen.setMinimumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lottozahlen.setFont(font)
        self.Lottozahlen.setAutoFillBackground(False)
        self.Lottozahlen.setStyleSheet(_fromUtf8("QFrame#Rahmen { border-image: url(:/lottokugel.png);}\n"
"QLabel {    background-color: rgb(195, 195, 195)}"))
        self.Lottozahlen.setObjectName(_fromUtf8("Lottozahlen"))
        self.gridLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 444, 251))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 290, 441, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_hinzu = QtGui.QPushButton(self.Lottozahlen)
        self.btn_hinzu.setGeometry(QtCore.QRect(220, 260, 231, 25))
        self.btn_hinzu.setObjectName(_fromUtf8("btn_hinzu"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 441, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lab_zusatz = QtGui.QLabel(self.Lottozahlen)
        self.lab_zusatz.setGeometry(QtCore.QRect(10, 360, 101, 21))
        self.lab_zusatz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_zusatz.setObjectName(_fromUtf8("lab_zusatz"))
        self.spinBox_superz = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_superz.setGeometry(QtCore.QRect(360, 360, 51, 23))
        self.spinBox_superz.setMaximum(9)
        self.spinBox_superz.setObjectName(_fromUtf8("spinBox_superz"))
        self.lab_superz = QtGui.QLabel(self.Lottozahlen)
        self.lab_superz.setGeometry(QtCore.QRect(240, 360, 91, 21))
        self.lab_superz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_superz.setObjectName(_fromUtf8("lab_superz"))
        self.spinBox_spiel77 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_spiel77.setGeometry(QtCore.QRect(130, 384, 101, 23))
        self.spinBox_spiel77.setMaximum(9999999)
        self.spinBox_spiel77.setObjectName(_fromUtf8("spinBox_spiel77"))
        self.lab_spiel77 = QtGui.QLabel(self.Lottozahlen)
        self.lab_spiel77.setGeometry(QtCore.QRect(10, 384, 101, 21))
        self.lab_spiel77.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_spiel77.setObjectName(_fromUtf8("lab_spiel77"))
        self.spinBox_super6 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_super6.setGeometry(QtCore.QRect(360, 384, 91, 23))
        self.spinBox_super6.setMaximum(999999)
        self.spinBox_super6.setObjectName(_fromUtf8("spinBox_super6"))
        self.lab_super6 = QtGui.QLabel(self.Lottozahlen)
        self.lab_super6.setGeometry(QtCore.QRect(240, 384, 91, 21))
        self.lab_super6.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_super6.setObjectName(_fromUtf8("lab_super6"))
        self.com_modus = QtGui.QComboBox(self.Lottozahlen)
        self.com_modus.setGeometry(QtCore.QRect(10, 260, 151, 25))
        self.com_modus.setObjectName(_fromUtf8("com_modus"))
        self.com_modus.addItem(_fromUtf8(""))
        self.com_modus.addItem(_fromUtf8(""))
        self.btn_zufall = QtGui.QPushButton(self.Lottozahlen)
        self.btn_zufall.setGeometry(QtCore.QRect(40, 350, 151, 21))
        self.btn_zufall.setObjectName(_fromUtf8("btn_zufall"))
        self.com_laufzeit = QtGui.QComboBox(self.Lottozahlen)
        self.com_laufzeit.setGeometry(QtCore.QRect(240, 384, 121, 23))
        self.com_laufzeit.setObjectName(_fromUtf8("com_laufzeit"))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.lab_laufzeit = QtGui.QLabel(self.Lottozahlen)
        self.lab_laufzeit.setGeometry(QtCore.QRect(280, 360, 69, 18))
        self.lab_laufzeit.setObjectName(_fromUtf8("lab_laufzeit"))
        self.btn_set_calender_today = QtGui.QPushButton(self.Lottozahlen)
        self.btn_set_calender_today.setGeometry(QtCore.QRect(10, 460, 141, 41))
        self.btn_set_calender_today.setObjectName(_fromUtf8("btn_set_calender_today"))
        self.lab_scheinnr = QtGui.QLabel(self.Lottozahlen)
        self.lab_scheinnr.setGeometry(QtCore.QRect(10, 384, 111, 21))
        self.lab_scheinnr.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_scheinnr.setObjectName(_fromUtf8("lab_scheinnr"))
        self.com_laufzeit_tag = QtGui.QComboBox(self.Lottozahlen)
        self.com_laufzeit_tag.setGeometry(QtCore.QRect(370, 384, 91, 23))
        self.com_laufzeit_tag.setObjectName(_fromUtf8("com_laufzeit_tag"))
        self.com_laufzeit_tag.addItem(_fromUtf8(""))
        self.com_laufzeit_tag.addItem(_fromUtf8(""))
        self.com_laufzeit_tag.addItem(_fromUtf8(""))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(470, -1, 421, 431))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.edi_daten_gewinnz = QtGui.QPlainTextEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.edi_daten_gewinnz.setFont(font)
        self.edi_daten_gewinnz.setAutoFillBackground(False)
        self.edi_daten_gewinnz.setUndoRedoEnabled(False)
        self.edi_daten_gewinnz.setReadOnly(True)
        self.edi_daten_gewinnz.setObjectName(_fromUtf8("edi_daten_gewinnz"))
        self.verticalLayout.addWidget(self.edi_daten_gewinnz)
        self.lab_daten_gewinnz = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.lab_daten_gewinnz.setObjectName(_fromUtf8("lab_daten_gewinnz"))
        self.verticalLayout.addWidget(self.lab_daten_gewinnz)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Btn_gz_anzeigen = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.Btn_gz_anzeigen.setObjectName(_fromUtf8("Btn_gz_anzeigen"))
        self.horizontalLayout_3.addWidget(self.Btn_gz_anzeigen)
        self.Btn_gz_loeschen = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.Btn_gz_loeschen.setEnabled(True)
        self.Btn_gz_loeschen.setObjectName(_fromUtf8("Btn_gz_loeschen"))
        self.horizontalLayout_3.addWidget(self.Btn_gz_loeschen)
        self.CBox_gz_kompl_ausgeben = QtGui.QCheckBox(self.horizontalLayoutWidget_5)
        self.CBox_gz_kompl_ausgeben.setObjectName(_fromUtf8("CBox_gz_kompl_ausgeben"))
        self.horizontalLayout_3.addWidget(self.CBox_gz_kompl_ausgeben)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.edi_daten_lottoschein = QtGui.QPlainTextEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(9)
        self.edi_daten_lottoschein.setFont(font)
        self.edi_daten_lottoschein.setAutoFillBackground(False)
        self.edi_daten_lottoschein.setUndoRedoEnabled(False)
        self.edi_daten_lottoschein.setReadOnly(True)
        self.edi_daten_lottoschein.setObjectName(_fromUtf8("edi_daten_lottoschein"))
        self.verticalLayout.addWidget(self.edi_daten_lottoschein)
        self.lab_daten_lottoschein = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.lab_daten_lottoschein.setObjectName(_fromUtf8("lab_daten_lottoschein"))
        self.verticalLayout.addWidget(self.lab_daten_lottoschein)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_ls_auswerten = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.btn_ls_auswerten.setObjectName(_fromUtf8("btn_ls_auswerten"))
        self.horizontalLayout_4.addWidget(self.btn_ls_auswerten)
        self.Btn_ls_anzeigen = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.Btn_ls_anzeigen.setObjectName(_fromUtf8("Btn_ls_anzeigen"))
        self.horizontalLayout_4.addWidget(self.Btn_ls_anzeigen)
        self.Btn_ls_loeschen = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.Btn_ls_loeschen.setObjectName(_fromUtf8("Btn_ls_loeschen"))
        self.horizontalLayout_4.addWidget(self.Btn_ls_loeschen)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 420, 326, 33))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_tag = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_tag.setObjectName(_fromUtf8("label_tag"))
        self.horizontalLayout_6.addWidget(self.label_tag)
        self.spinbox_tag = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinbox_tag.setMinimum(1)
        self.spinbox_tag.setMaximum(31)
        self.spinbox_tag.setObjectName(_fromUtf8("spinbox_tag"))
        self.horizontalLayout_6.addWidget(self.spinbox_tag)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_monat = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_monat.setObjectName(_fromUtf8("label_monat"))
        self.horizontalLayout_6.addWidget(self.label_monat)
        self.spinBox_monat = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_monat.sizePolicy().hasHeightForWidth())
        self.spinBox_monat.setSizePolicy(sizePolicy)
        self.spinBox_monat.setMinimum(1)
        self.spinBox_monat.setMaximum(12)
        self.spinBox_monat.setObjectName(_fromUtf8("spinBox_monat"))
        self.horizontalLayout_6.addWidget(self.spinBox_monat)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_jahr = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_jahr.setObjectName(_fromUtf8("label_jahr"))
        self.horizontalLayout_6.addWidget(self.label_jahr)
        self.spinBox_jahr = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_jahr.sizePolicy().hasHeightForWidth())
        self.spinBox_jahr.setSizePolicy(sizePolicy)
        self.spinBox_jahr.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_jahr.setMinimum(1900)
        self.spinBox_jahr.setMaximum(2300)
        self.spinBox_jahr.setObjectName(_fromUtf8("spinBox_jahr"))
        self.horizontalLayout_6.addWidget(self.spinBox_jahr)
        self.btn_kalender = QtGui.QPushButton(self.Lottozahlen)
        self.btn_kalender.setGeometry(QtCore.QRect(170, 460, 141, 41))
        self.btn_kalender.setObjectName(_fromUtf8("btn_kalender"))
        MainWindow.setCentralWidget(self.Lottozahlen)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuInternet = QtGui.QMenu(self.menubar)
        self.menuInternet.setObjectName(_fromUtf8("menuInternet"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionHilfe = QtGui.QAction(MainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.actionDaten_von_lotto_de = QtGui.QAction(MainWindow)
        self.actionDaten_von_lotto_de.setObjectName(_fromUtf8("actionDaten_von_lotto_de"))
        self.actionDaten_von_lottozahlenonline_de_2010_2013 = QtGui.QAction(MainWindow)
        self.actionDaten_von_lottozahlenonline_de_2010_2013.setObjectName(_fromUtf8("actionDaten_von_lottozahlenonline_de_2010_2013"))
        self.actionDaten_von_lottozahlenonline_de_2000_2004 = QtGui.QAction(MainWindow)
        self.actionDaten_von_lottozahlenonline_de_2000_2004.setObjectName(_fromUtf8("actionDaten_von_lottozahlenonline_de_2000_2004"))
        self.actionDaten_von_lottozahlenonline_de_2005_2009 = QtGui.QAction(MainWindow)
        self.actionDaten_von_lottozahlenonline_de_2005_2009.setObjectName(_fromUtf8("actionDaten_von_lottozahlenonline_de_2005_2009"))
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionInfo)
        self.menuInternet.addAction(self.actionDaten_von_lotto_de)
        self.menuInternet.addAction(self.actionDaten_von_lottozahlenonline_de_2010_2013)
        self.menuInternet.addAction(self.actionDaten_von_lottozahlenonline_de_2000_2004)
        self.menuInternet.addAction(self.actionDaten_von_lottozahlenonline_de_2005_2009)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuInternet.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edi_daten_gewinnz, self.btn_hinzu)
        MainWindow.setTabOrder(self.btn_hinzu, self.com_modus)
        MainWindow.setTabOrder(self.com_modus, self.btn_zufall)
        MainWindow.setTabOrder(self.btn_zufall, self.com_laufzeit)
        MainWindow.setTabOrder(self.com_laufzeit, self.spinBox_superz)
        MainWindow.setTabOrder(self.spinBox_superz, self.spinBox_spiel77)
        MainWindow.setTabOrder(self.spinBox_spiel77, self.spinBox_super6)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.Lottozahlen.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_hinzu.setText(QtGui.QApplication.translate("MainWindow", "zur Datenbank hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_zusatz.setText(QtGui.QApplication.translate("MainWindow", "Zusatzzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_superz.setText(QtGui.QApplication.translate("MainWindow", "Superzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_spiel77.setText(QtGui.QApplication.translate("MainWindow", "Spiel 77", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_super6.setText(QtGui.QApplication.translate("MainWindow", "Super 6:", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gewinnzahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(1, QtGui.QApplication.translate("MainWindow", "Lottoschein", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_zufall.setText(QtGui.QApplication.translate("MainWindow", "Zufallszahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(0, QtGui.QApplication.translate("MainWindow", "unbegrenzt", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 Ziehung", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(3, QtGui.QApplication.translate("MainWindow", "3 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(4, QtGui.QApplication.translate("MainWindow", "4 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(5, QtGui.QApplication.translate("MainWindow", "5 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_laufzeit.setText(QtGui.QApplication.translate("MainWindow", "Laufzeit:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_set_calender_today.setText(QtGui.QApplication.translate("MainWindow", "Datum von heute\n"
"einstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_scheinnr.setText(QtGui.QApplication.translate("MainWindow", "Scheinnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit_tag.setItemText(0, QtGui.QApplication.translate("MainWindow", "Mi+Sa", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit_tag.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mittwoch", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit_tag.setItemText(2, QtGui.QApplication.translate("MainWindow", "Samstag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Gewinnzahlen:", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_gewinnz.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_gewinnz.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.CBox_gz_kompl_ausgeben.setText(QtGui.QApplication.translate("MainWindow", "alle Einträge", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lottoschein:", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_lottoschein.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_lottoschein.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ls_auswerten.setText(QtGui.QApplication.translate("MainWindow", "auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tag.setText(QtGui.QApplication.translate("MainWindow", "Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_monat.setText(QtGui.QApplication.translate("MainWindow", "Monat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_jahr.setText(QtGui.QApplication.translate("MainWindow", "Jahr", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_kalender.setText(QtGui.QApplication.translate("MainWindow", "Kalender\n"
"öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInternet.setTitle(QtGui.QApplication.translate("MainWindow", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe.setText(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaten_von_lotto_de.setText(QtGui.QApplication.translate("MainWindow", "Daten von lotto.de (aktuelle Ziehung)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaten_von_lottozahlenonline_de_2010_2013.setText(QtGui.QApplication.translate("MainWindow", "Daten von  lottozahlenonline.de (2010-2013)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaten_von_lottozahlenonline_de_2000_2004.setText(QtGui.QApplication.translate("MainWindow", "Daten von  lottozahlenonline.de (2000-2004)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaten_von_lottozahlenonline_de_2005_2009.setText(QtGui.QApplication.translate("MainWindow", "Daten von  lottozahlenonline.de (2005-2009)", None, QtGui.QApplication.UnicodeUTF8))

