# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotto_dateneing.ui'
#
# Created: Mon Dec 31 00:51:01 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(894, 665)
        self.Lottozahlen = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lottozahlen.sizePolicy().hasHeightForWidth())
        self.Lottozahlen.setSizePolicy(sizePolicy)
        self.Lottozahlen.setMinimumSize(QtCore.QSize(480, 320))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Lottozahlen.setFont(font)
        self.Lottozahlen.setAutoFillBackground(False)
        self.Lottozahlen.setStyleSheet(_fromUtf8("QFrame#Rahmen { border-image: url(:/lottokugel.png);}\n"
"QLabel {    background-color: rgb(195, 195, 195)}"))
        self.Lottozahlen.setObjectName(_fromUtf8("Lottozahlen"))
        self.gridLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 444, 251))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edi_daten_gewinnz = QtGui.QPlainTextEdit(self.Lottozahlen)
        self.edi_daten_gewinnz.setGeometry(QtCore.QRect(470, 30, 401, 151))
        self.edi_daten_gewinnz.setAutoFillBackground(False)
        self.edi_daten_gewinnz.setUndoRedoEnabled(False)
        self.edi_daten_gewinnz.setReadOnly(True)
        self.edi_daten_gewinnz.setObjectName(_fromUtf8("edi_daten_gewinnz"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 290, 441, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.calendarWidget = QtGui.QCalendarWidget(self.Lottozahlen)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 408, 361, 200))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtGui.QCalendarWidget.SingleSelection)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.Btn_hinzu = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_hinzu.setGeometry(QtCore.QRect(220, 260, 231, 25))
        self.Btn_hinzu.setObjectName(_fromUtf8("Btn_hinzu"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 320, 441, 31))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lab_zusatz = QtGui.QLabel(self.Lottozahlen)
        self.lab_zusatz.setGeometry(QtCore.QRect(10, 360, 101, 21))
        self.lab_zusatz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_zusatz.setObjectName(_fromUtf8("lab_zusatz"))
        self.spinBox_superz = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_superz.setGeometry(QtCore.QRect(360, 360, 51, 23))
        self.spinBox_superz.setMaximum(9)
        self.spinBox_superz.setObjectName(_fromUtf8("spinBox_superz"))
        self.lab_superz = QtGui.QLabel(self.Lottozahlen)
        self.lab_superz.setGeometry(QtCore.QRect(240, 360, 91, 21))
        self.lab_superz.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_superz.setObjectName(_fromUtf8("lab_superz"))
        self.spinBox_spiel77 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_spiel77.setGeometry(QtCore.QRect(130, 384, 101, 23))
        self.spinBox_spiel77.setMaximum(9999999)
        self.spinBox_spiel77.setObjectName(_fromUtf8("spinBox_spiel77"))
        self.lab_spiel77 = QtGui.QLabel(self.Lottozahlen)
        self.lab_spiel77.setGeometry(QtCore.QRect(10, 384, 101, 21))
        self.lab_spiel77.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_spiel77.setObjectName(_fromUtf8("lab_spiel77"))
        self.spinBox_super6 = QtGui.QSpinBox(self.Lottozahlen)
        self.spinBox_super6.setGeometry(QtCore.QRect(360, 384, 91, 23))
        self.spinBox_super6.setMaximum(999999)
        self.spinBox_super6.setObjectName(_fromUtf8("spinBox_super6"))
        self.lab_super6 = QtGui.QLabel(self.Lottozahlen)
        self.lab_super6.setGeometry(QtCore.QRect(240, 384, 91, 21))
        self.lab_super6.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_super6.setObjectName(_fromUtf8("lab_super6"))
        self.com_modus = QtGui.QComboBox(self.Lottozahlen)
        self.com_modus.setGeometry(QtCore.QRect(10, 260, 151, 25))
        self.com_modus.setObjectName(_fromUtf8("com_modus"))
        self.com_modus.addItem(_fromUtf8(""))
        self.com_modus.addItem(_fromUtf8(""))
        self.Btn_Zufall = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_Zufall.setGeometry(QtCore.QRect(40, 350, 151, 21))
        self.Btn_Zufall.setObjectName(_fromUtf8("Btn_Zufall"))
        self.com_laufzeit = QtGui.QComboBox(self.Lottozahlen)
        self.com_laufzeit.setGeometry(QtCore.QRect(240, 384, 121, 23))
        self.com_laufzeit.setObjectName(_fromUtf8("com_laufzeit"))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.com_laufzeit.addItem(_fromUtf8(""))
        self.lab_laufzeit = QtGui.QLabel(self.Lottozahlen)
        self.lab_laufzeit.setGeometry(QtCore.QRect(280, 360, 69, 18))
        self.lab_laufzeit.setObjectName(_fromUtf8("lab_laufzeit"))
        self.edi_daten_lottoschein = QtGui.QPlainTextEdit(self.Lottozahlen)
        self.edi_daten_lottoschein.setGeometry(QtCore.QRect(470, 340, 401, 161))
        self.edi_daten_lottoschein.setAutoFillBackground(False)
        self.edi_daten_lottoschein.setUndoRedoEnabled(False)
        self.edi_daten_lottoschein.setReadOnly(True)
        self.edi_daten_lottoschein.setObjectName(_fromUtf8("edi_daten_lottoschein"))
        self.label = QtGui.QLabel(self.Lottozahlen)
        self.label.setGeometry(QtCore.QRect(610, 310, 121, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.Lottozahlen)
        self.label_2.setGeometry(QtCore.QRect(600, 0, 111, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lab_daten_gewinnz = QtGui.QLabel(self.Lottozahlen)
        self.lab_daten_gewinnz.setGeometry(QtCore.QRect(470, 180, 401, 51))
        self.lab_daten_gewinnz.setObjectName(_fromUtf8("lab_daten_gewinnz"))
        self.lab_daten_lottoschein = QtGui.QLabel(self.Lottozahlen)
        self.lab_daten_lottoschein.setGeometry(QtCore.QRect(470, 500, 401, 51))
        self.lab_daten_lottoschein.setObjectName(_fromUtf8("lab_daten_lottoschein"))
        self.Btn_set_calender_today = QtGui.QPushButton(self.Lottozahlen)
        self.Btn_set_calender_today.setGeometry(QtCore.QRect(380, 440, 71, 31))
        self.Btn_set_calender_today.setObjectName(_fromUtf8("Btn_set_calender_today"))
        self.lab_scheinnr = QtGui.QLabel(self.Lottozahlen)
        self.lab_scheinnr.setGeometry(QtCore.QRect(10, 384, 101, 21))
        self.lab_scheinnr.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_scheinnr.setObjectName(_fromUtf8("lab_scheinnr"))
        self.com_laufzeit_tag = QtGui.QComboBox(self.Lottozahlen)
        self.com_laufzeit_tag.setGeometry(QtCore.QRect(370, 384, 91, 23))
        self.com_laufzeit_tag.setObjectName(_fromUtf8("com_laufzeit_tag"))
        self.com_laufzeit_tag.addItem(_fromUtf8(""))
        self.com_laufzeit_tag.addItem(_fromUtf8(""))
        self.com_laufzeit_tag.addItem(_fromUtf8(""))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(470, 240, 401, 33))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Btn_gz_auswerten = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_gz_auswerten.setAutoFillBackground(False)
        self.Btn_gz_auswerten.setStyleSheet(_fromUtf8(""))
        self.Btn_gz_auswerten.setObjectName(_fromUtf8("Btn_gz_auswerten"))
        self.horizontalLayout_3.addWidget(self.Btn_gz_auswerten)
        self.Btn_gz_anzeigen = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_gz_anzeigen.setObjectName(_fromUtf8("Btn_gz_anzeigen"))
        self.horizontalLayout_3.addWidget(self.Btn_gz_anzeigen)
        self.Btn_gz_loeschen = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.Btn_gz_loeschen.setEnabled(True)
        self.Btn_gz_loeschen.setObjectName(_fromUtf8("Btn_gz_loeschen"))
        self.horizontalLayout_3.addWidget(self.Btn_gz_loeschen)
        self.CBox_gz_kompl_ausgeben = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.CBox_gz_kompl_ausgeben.setObjectName(_fromUtf8("CBox_gz_kompl_ausgeben"))
        self.horizontalLayout_3.addWidget(self.CBox_gz_kompl_ausgeben)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.Lottozahlen)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(470, 560, 401, 33))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Btn_ls_auswerten = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ls_auswerten.setObjectName(_fromUtf8("Btn_ls_auswerten"))
        self.horizontalLayout_4.addWidget(self.Btn_ls_auswerten)
        self.Btn_ls_anzeigen = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ls_anzeigen.setObjectName(_fromUtf8("Btn_ls_anzeigen"))
        self.horizontalLayout_4.addWidget(self.Btn_ls_anzeigen)
        self.Btn_ls_loeschen = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.Btn_ls_loeschen.setObjectName(_fromUtf8("Btn_ls_loeschen"))
        self.horizontalLayout_4.addWidget(self.Btn_ls_loeschen)
        MainWindow.setCentralWidget(self.Lottozahlen)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName(_fromUtf8("menuDatei"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuInternet = QtGui.QMenu(self.menubar)
        self.menuInternet.setObjectName(_fromUtf8("menuInternet"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionHilfe = QtGui.QAction(MainWindow)
        self.actionHilfe.setObjectName(_fromUtf8("actionHilfe"))
        self.actionDaten_von_lotto_de = QtGui.QAction(MainWindow)
        self.actionDaten_von_lotto_de.setObjectName(_fromUtf8("actionDaten_von_lotto_de"))
        self.actionDaten_von_lottozahlenonline_de_1955_2012 = QtGui.QAction(MainWindow)
        self.actionDaten_von_lottozahlenonline_de_1955_2012.setObjectName(_fromUtf8("actionDaten_von_lottozahlenonline_de_1955_2012"))
        self.menuDatei.addAction(self.actionBeenden)
        self.menuHilfe.addAction(self.actionInfo)
        self.menuInternet.addAction(self.actionDaten_von_lotto_de)
        self.menuInternet.addAction(self.actionDaten_von_lottozahlenonline_de_1955_2012)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuInternet.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.edi_daten_gewinnz, self.calendarWidget)
        MainWindow.setTabOrder(self.calendarWidget, self.Btn_hinzu)
        MainWindow.setTabOrder(self.Btn_hinzu, self.com_modus)
        MainWindow.setTabOrder(self.com_modus, self.Btn_Zufall)
        MainWindow.setTabOrder(self.Btn_Zufall, self.com_laufzeit)
        MainWindow.setTabOrder(self.com_laufzeit, self.spinBox_superz)
        MainWindow.setTabOrder(self.spinBox_superz, self.spinBox_spiel77)
        MainWindow.setTabOrder(self.spinBox_spiel77, self.spinBox_super6)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.Lottozahlen.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lottozahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_gewinnz.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_hinzu.setText(QtGui.QApplication.translate("MainWindow", "zur Datenbank hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_zusatz.setText(QtGui.QApplication.translate("MainWindow", "Zusatzzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_superz.setText(QtGui.QApplication.translate("MainWindow", "Superzahl", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_spiel77.setText(QtGui.QApplication.translate("MainWindow", "Spiel 77", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_super6.setText(QtGui.QApplication.translate("MainWindow", "Super 6:", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gewinnzahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_modus.setItemText(1, QtGui.QApplication.translate("MainWindow", "Lottoschein", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_Zufall.setText(QtGui.QApplication.translate("MainWindow", "Zufallszahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(0, QtGui.QApplication.translate("MainWindow", "unbegrenzt", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 Ziehung", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(3, QtGui.QApplication.translate("MainWindow", "3 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(4, QtGui.QApplication.translate("MainWindow", "4 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit.setItemText(5, QtGui.QApplication.translate("MainWindow", "5 Ziehungen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_laufzeit.setText(QtGui.QApplication.translate("MainWindow", "Laufzeit:", None, QtGui.QApplication.UnicodeUTF8))
        self.edi_daten_lottoschein.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Ausgabefeld", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lottoschein:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Gewinnzahlen:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_gewinnz.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_daten_lottoschein.setText(QtGui.QApplication.translate("MainWindow", "Gewählter Datensatz", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_set_calender_today.setText(QtGui.QApplication.translate("MainWindow", "heute", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_scheinnr.setText(QtGui.QApplication.translate("MainWindow", "Scheinnummer", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit_tag.setItemText(0, QtGui.QApplication.translate("MainWindow", "Mi+Sa", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit_tag.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mittwoch", None, QtGui.QApplication.UnicodeUTF8))
        self.com_laufzeit_tag.setItemText(2, QtGui.QApplication.translate("MainWindow", "Samstag", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_auswerten.setText(QtGui.QApplication.translate("MainWindow", "Auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_gz_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.CBox_gz_kompl_ausgeben.setText(QtGui.QApplication.translate("MainWindow", "alle Einträge", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_auswerten.setText(QtGui.QApplication.translate("MainWindow", "Auswerten", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_anzeigen.setText(QtGui.QApplication.translate("MainWindow", "anzeigen", None, QtGui.QApplication.UnicodeUTF8))
        self.Btn_ls_loeschen.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInternet.setTitle(QtGui.QApplication.translate("MainWindow", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe.setText(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaten_von_lotto_de.setText(QtGui.QApplication.translate("MainWindow", "Daten von lotto.de (aktuelle Ziehung)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaten_von_lottozahlenonline_de_1955_2012.setText(QtGui.QApplication.translate("MainWindow", "Daten von  lottozahlenonline.de (2000-2012)", None, QtGui.QApplication.UnicodeUTF8))

